#!/usr/bin/env bash
set -ex # se lo script fallisce ferma l'esecuzione

if [ ! -d ./venv ]; then
	python -m venv venv

fi
source venv/bin/activate
pip install -r requirements.txt
python "src/app/app.py"
deactivate 
